apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-amqp-py
    name: mizutest-amqp-py
    version: v0.1.0
  name: mizutest-amqp-py
  namespace: sock-shop
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    name: mizutest-amqp-py
