apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: sock-shop
spec:
  clusterIP: None
  ports:
  - name: plaintext
    port: 9092
  - name: jmx
    port: 9999
  selector:
    app: kafka
