apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-kafka-py
    name: mizutest-kafka-py
    version: v0.1.0
  name: mizutest-kafka-py
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-kafka-py
  template:
    metadata:
      labels:
        app: mizutest-kafka-py
        name: mizutest-kafka-py
        version: v0.1.0
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./run.sh > /dev/null 2>&1
        image: mertyildiran/mizutest-kafka-py:latest
        imagePullPolicy: Always
        name: mizutest-kafka-py
        ports:
        - containerPort: 9092
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
      nodeSelector:
        kubernetes.io/os: linux
