apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-kafka-go
    name: mizutest-kafka-go
    version: v0.1.0
  name: mizutest-kafka-go
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-kafka-go
  template:
    metadata:
      labels:
        app: mizutest-kafka-go
        name: mizutest-kafka-go
        version: v0.1.0
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./run.sh > /dev/null 2>&1
        image: mertyildiran/mizutest-kafka-go:latest
        imagePullPolicy: Always
        name: mizutest-kafka-go
        ports:
        - containerPort: 9092
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        kubernetes.io/os: linux
