---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizutest-kafka-go
  labels:
    name: mizutest-kafka-go
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-kafka-go
  template:
    metadata:
      labels:
        name: mizutest-kafka-go
    spec:
      containers:
      - name: mizutest-kafka-go
        image: mertyildiran/mizutest-kafka-go:latest
        imagePullPolicy: Always
        command: ["sh", "-c",  "./run.sh > /dev/null 2>&1"]
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 9092
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 10001
        #   capabilities:
        #     drop:
        #       - all
        #     add:
        #       - NET_BIND_SERVICE
        #   readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
