apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-kafka-go
    name: mizutest-kafka-go
    version: v0.1.0
  name: mizutest-kafka-go
  namespace: sock-shop
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    name: mizutest-kafka-go
