---
apiVersion: v1
kind: Service
metadata:
  name: mizutest-redis-go
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: mizutest-redis-go
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: mizutest-redis-go
