apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-redis-go
    name: mizutest-redis-go
    version: v0.1.0
  name: mizutest-redis-go
  namespace: sock-shop
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: mizutest-redis-go
