apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-grpc-py-server
    name: mizutest-grpc-py-server
    version: v0.1.0
  name: mizutest-grpc-py-server
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-grpc-py-server
  template:
    metadata:
      labels:
        app: mizutest-grpc-py-server
        name: mizutest-grpc-py-server
        version: v0.1.0
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./run.sh > /dev/null 2>&1
        env:
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: PYTHONIOENCODING
          value: UTF-8
        image: mertyildiran/mizutest-grpc-py-server:latest
        imagePullPolicy: Always
        name: mizutest-grpc-py-server
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
      nodeSelector:
        kubernetes.io/os: linux
