apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-grpc-py-server
    name: mizutest-grpc-py-server
    version: v0.1.0
  name: mizutest-grpc-py-server
  namespace: sock-shop
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    name: mizutest-grpc-py-server
