apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-test
    name: load-test
    version: v0.1.0
  name: load-test
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        app: load-test
        name: load-test
        version: v0.1.0
    spec:
      containers:
      - args:
        - -c
        - while true; do locust --host http://front-end.sock-shop.svc.cluster.local
          -f /config/locustfile.py --clients 1 --hatch-rate 1 --num-request 10 --no-web;
          done
        command:
        - /bin/sh
        image: weaveworksdemos/load-test:0.1.1
        name: load-test
      nodeSelector:
        kubernetes.io/os: linux
