apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-outbound-tls-openssl
    name: mizutest-outbound-tls-openssl
    version: v0.1.0
  name: mizutest-outbound-tls-openssl
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-outbound-tls-openssl
  template:
    metadata:
      labels:
        app: mizutest-outbound-tls-openssl
        name: mizutest-outbound-tls-openssl
        version: v0.1.0
    spec:
      containers:
      - command:
        - python3
        - example.py
        env:
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: PYTHONIOENCODING
          value: UTF-8
        image: mertyildiran/mizutest-outbound-tls-openssl:latest
        imagePullPolicy: Always
        name: mizutest-outbound-tls-openssl
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        kubernetes.io/os: linux
