---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizutest-outbound-tls-openssl
  labels:
    name: mizutest-outbound-tls-openssl
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-outbound-tls-openssl
  template:
    metadata:
      labels:
        name: mizutest-outbound-tls-openssl
    spec:
      containers:
      - name: mizutest-outbound-tls-openssl
        image: mertyildiran/mizutest-outbound-tls-openssl:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
        imagePullPolicy: Always
        command: ["python3", "example.py"]
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 10001
        #   capabilities:
        #     drop:
        #       - all
        #     add:
        #       - NET_BIND_SERVICE
        #   readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
