apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-outbound-tls-openssl
    name: mizutest-outbound-tls-openssl
    version: v0.1.0
  name: mizutest-outbound-tls-openssl
  namespace: sock-shop
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: mizutest-outbound-tls-openssl
