apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-graphql-server
    name: mizutest-graphql-server
    version: v0.1.0
  name: mizutest-graphql-server
  namespace: sock-shop
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: mizutest-graphql-server
