apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mizutest-outbound-tls-golang
    name: mizutest-outbound-tls-golang
    version: v0.1.0
  name: mizutest-outbound-tls-golang
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-outbound-tls-golang
  template:
    metadata:
      labels:
        app: mizutest-outbound-tls-golang
        name: mizutest-outbound-tls-golang
        version: v0.1.0
    spec:
      containers:
      - command:
        - ./main
        image: mertyildiran/mizutest-outbound-tls-golang:latest
        imagePullPolicy: Always
        name: mizutest-outbound-tls-golang
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
      nodeSelector:
        kubernetes.io/os: linux
