---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizutest-outbound-tls-golang-1-16
  labels:
    name: mizutest-outbound-tls-golang-1-16
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mizutest-outbound-tls-golang-1-16
  template:
    metadata:
      labels:
        name: mizutest-outbound-tls-golang-1-16
    spec:
      containers:
      - name: mizutest-outbound-tls-golang-1-16
        image: mertyildiran/mizutest-outbound-tls-golang-1.16:latest
        imagePullPolicy: Always
        command: ["./main"]
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 10001
        #   capabilities:
        #     drop:
        #       - all
        #     add:
        #       - NET_BIND_SERVICE
        #   readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
