apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-websocket-client
    name: mizutest-websocket-client
    version: v0.1.0
  name: mizutest-websocket-client
  namespace: sock-shop
spec:
  ports:
  - port: 5672
    targetPort: 5672
  selector:
    name: mizutest-websocket-client
