---
apiVersion: v1
kind: Service
metadata:
  name: mizutest-inbound-tls-golang-server
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: mizutest-inbound-tls-golang-server
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 443
    targetPort: 443
  selector:
    name: mizutest-inbound-tls-golang-server
