---
apiVersion: v1
kind: Service
metadata:
  name: mizutest-inbound-tls-nodejs-server
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: mizutest-inbound-tls-nodejs-server
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 8000
    targetPort: 8000
  selector:
    name: mizutest-inbound-tls-nodejs-server
