---
apiVersion: v1
kind: Service
metadata:
  name: mizutest-outbound-tls-golang-1-16
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: mizutest-outbound-tls-golang-1-16
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: mizutest-outbound-tls-golang-1-16
