apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-sctp-server
    name: mizutest-sctp-server
    version: v0.1.0
  name: mizutest-sctp-server
  namespace: sock-shop
spec:
  clusterIP: None
  ports:
  - port: 50051
    protocol: SCTP
    targetPort: 50051
  selector:
    name: mizutest-sctp-server
