apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mizutest-sctp-client
    name: mizutest-sctp-client
    version: v0.1.0
  name: mizutest-sctp-client
  namespace: sock-shop
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    name: mizutest-sctp-client
