apiVersion: v1
kind: Service
metadata:
  labels:
    app: carts-db
    name: carts-db
    version: v0.1.0
  name: carts-db
  namespace: sock-shop
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: carts-db
    name: carts-db
    version: v0.1.0
