apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue-db
    name: catalogue-db
    version: v0.1.0
  name: catalogue-db
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-db
      name: catalogue-db
      version: v0.1.0
  template:
    metadata:
      labels:
        app: catalogue-db
        name: catalogue-db
        version: v0.1.0
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: fake_password
        - name: MYSQL_DATABASE
          value: socksdb
        image: weaveworksdemos/catalogue-db:0.3.0
        name: catalogue-db
        ports:
        - containerPort: 3306
          name: mysql
      nodeSelector:
        kubernetes.io/os: linux
