apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    name: rabbitmq
    version: v0.1.0
  name: rabbitmq
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      name: rabbitmq
      version: v0.1.0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'false'
      labels:
        app: rabbitmq
        name: rabbitmq
        version: v0.1.0
    spec:
      containers:
      - image: rabbitmq:3.6.8-management
        name: rabbitmq
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            drop:
            - all
          readOnlyRootFilesystem: true
      - image: kbudde/rabbitmq-exporter
        name: rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      nodeSelector:
        kubernetes.io/os: linux
