apiVersion: v1
kind: Service
metadata:
  labels:
    app: session-db
    name: session-db
    version: v0.1.0
  name: session-db
  namespace: sock-shop
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: session-db
    name: session-db
    version: v0.1.0
