---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    name: session-db
    app: session-db
    version: v0.1.0
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: session-db
    app: session-db
    version: v0.1.0