---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
    app: user-db
    version: v0.1.0
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: user-db
    app: user-db
    version: v0.1.0

