apiVersion: v1
kind: Service
metadata:
  name: mizu-internet-access
  namespace: sock-shop
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8899
  selector:
    app: mizu-api-server
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster